### ISSUE TITLE
Memory leaks on task operations

### ISSUE THREAD

**Issue by yatskovsky** [aerospike/aerospike-client-csharp#12]
Hi,

The client (3.1.5, installed via Nuget) leaks after any asynchronous operation involving tasks. Every task leaves some objects in memory, even after the client is closed and disposed. 

RunPutGetWithTask()  from AsyncPutGet.cs could be a test example.

![2015-09-21_140110](https://cloud.githubusercontent.com/assets/14548407/9990624/6832508a-606b-11e5-8f12-1d5dc13b0d79.png)

**Comment by BrianNichols** [comment]
Can you replace ListenerAdapter.cs with the following code and let us know if that fixes the memory leak you are observing?

```
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Aerospike.Client
{
	internal abstract class ListenerAdapter<T>
	{
		private readonly TaskCompletionSource<T> tcs = new TaskCompletionSource<T>();
		private readonly CancellationTokenRegistration ctr;

		public ListenerAdapter(CancellationToken token)
		{
			ctr = token.Register(() => tcs.TrySetCanceled(), useSynchronizationContext: false);
		}

		protected void SetResult(T result)
		{
			tcs.TrySetResult(result);
			ctr.Dispose();
		}

		public void OnFailure(AerospikeException exception)
		{
			tcs.SetException(exception);
			ctr.Dispose();
		}

		public System.Threading.Tasks.Task<T> Task { get { return tcs.Task; } }
	}
}
```

**Comment by yatskovsky** [comment]
Hi,

I did, but now I see the problem with the whole callbacks mechanism, not solely tasks.

I added GC .Collect() to DemoForm.cs and set breakpoints.
![1](https://cloud.githubusercontent.com/assets/14548407/10726437/c94898d2-7be3-11e5-9d35-43426054a36a.png)

Any sync command does not grow memory after each succesive run (only the first time).

But any async command leaves extra bytes. E.g., Async scan. The difference between the last and previous run:
![2](https://cloud.githubusercontent.com/assets/14548407/10726490/0d48b3f0-7be4-11e5-9b00-ceedac5fada2.png)

And the difference between the last and second run:
![3](https://cloud.githubusercontent.com/assets/14548407/10726526/37ddea36-7be4-11e5-8fe3-afe0a4725d9c.png)

Memory usage grows linearly, exactly +40 ContextCallbacks (and other objects) for each run.

**Comment by BrianNichols** [comment]
What operating system, C# interpreter (MS or Mono) and memory profiler are you using?

**Comment by yatskovsky** [comment]
Windows 8.1 x64, Visual Studio 2015, built-in debug tool.

**Comment by BrianNichols** [comment]
We are able to replicate your "memory snapshot" observations with Visual Studio 15.  What you witnessed is:

1) SocketAsyncEventArgs instances are being cached in the cluster's argsQueue and then shared among newly created commands.

2) The garbage collector is delaying freeing of other unreferenced resources even though GC.Collect() was called. GC.Collect() is just a hint there are no guarantees that anything will be released.

If memory was truly being leaked, the application memory size would grow continuously and eventually crash.  We ran the asynchronous benchmarks in AerospikeDemo for an extended period of time.  The Task Manager showed AerospikeDemo memory size:

1) Starting at 9 MB just to bring up the application's main window. 

2) Jumping to 14 MB once asynchronous benchmarks is started.   This is due to various caches being populated.

3) Fluctuating between 14 - 20 MB during the asynchronous benchmarks.  Performance was constant and cpu/memory usage was steady during this time.
